### ISSUE TITLE
Debug IP adresy v configu

### ISSUE THREAD

**Issue by danielkucera** [petrbrouzda/RatatoskrIoT#3]
https://github.com/petrbrouzda/RatatoskrIoT/blob/d174414085b317ffe74eddb6b8230e717c849f33/server/php-app/app/Bootstrap.php#L16

toto by mohlo ist do configu namiesto "hardcoded" hodnoty

**Comment by petrbrouzda** [comment]
Jenže v době, kdy se tohle zpracovává, aplikace ještě neexistuje (celý ten cirkus ještě není nastartovaný) = konfigurace není načtená. Takhle se to prostě v Nette dělá.
https://doc.nette.org/cs/3.0/bootstrap#toc-vyvojarsky-vs-produkcni-rezim
